// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prigione.Data;

#nullable disable

namespace Prigione.Migrations
{
    [DbContext(typeof(PrigioneDbContext))]
    partial class PrigioneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prigione.Models.TrasgressoreModel", b =>
                {
                    b.Property<Guid>("TrasgressoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CAP")
                        .HasColumnType("int");

                    b.Property<string>("CF")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrasgressoreID");

                    b.ToTable("Trasgressori");
                });

            modelBuilder.Entity("Prigione.Models.VerbaleModel", b =>
                {
                    b.Property<Guid>("VerbaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVerbale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViolazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrasgressoreID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViolazioneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViolazioneID1")
                        .HasColumnType("int");

                    b.HasKey("VerbaleID");

                    b.HasIndex("TrasgressoreID");

                    b.HasIndex("ViolazioneID1");

                    b.ToTable("Verbali");
                });

            modelBuilder.Entity("Prigione.Models.ViolazioneModel", b =>
                {
                    b.Property<int>("ViolazioneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolazioneID"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ViolazioneID");

                    b.ToTable("Violazioni");
                });

            modelBuilder.Entity("Prigione.Models.VerbaleModel", b =>
                {
                    b.HasOne("Prigione.Models.TrasgressoreModel", "Trasgressore")
                        .WithMany("Verbali")
                        .HasForeignKey("TrasgressoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prigione.Models.ViolazioneModel", "Violazione")
                        .WithMany()
                        .HasForeignKey("ViolazioneID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trasgressore");

                    b.Navigation("Violazione");
                });

            modelBuilder.Entity("Prigione.Models.TrasgressoreModel", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
